version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chatbot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: chatbot_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
      # Initial setup scripts (optional)
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-chatbot_user} -d ${POSTGRES_DB:-chatbot_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chatbot_network

volumes:
  postgres_data:
    driver: local

networks:
  chatbot_network:
    driver: bridge
